version: '3.8'

services:
  zerochat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/zerochat:ro
    tty: true
    env_file: .env
    restart: on-failure
